apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: campusfix-backend
spec:
  ingressClassName: nginx
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: campusfix-backend
                port:
                  number: 80
